version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - ./env/backend.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql
    ports:
      - '8000:8000'
    container_name: insta-backend
  mysql:
    image: 'mysql:8.0.30'
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
    ports:
      - '3306:3306'
    container_name: mysqldb

volumes:
  data: