version: '3.8'
services:
  users-api:
    build: ./backend/users-api
    env_file:
      - ./env/users-api.env
    volumes:
      - ./backend/users-api:/app
      - /app/node_modules
    depends_on:
      - mysql
    container_name: users-api
  auth-api:
    build: ./backend/auth-api
    env_file:
      - ./env/auth-api.env
    volumes:
      - ./backend/auth-api:/app
      - /app/node_modules
    depends_on:
      - mysql
    container_name: auth-api
  posts-api:
    build: ./backend/posts-api
    env_file:
      - ./env/posts-api.env
    volumes:
      - ./backend/posts-api:/app
      - /app/node_modules
    depends_on:
      - mysql
    container_name: posts-api
  mysql:
    image: 'mysql:8.0.30'
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
    container_name: mysqldb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    # image: yeongbin/insta-frontend
    env_file:
      - ./env/frontend.env
    ports:
      - '80:80'
    depends_on:
      - users-api
      - auth-api
      - posts-api
    container_name: insta-frontend

volumes:
  data: