version: '3.8'
services:
  users-api:
    build: ./backend/users-api
    env_file:
      - ./env/users-api.env
    volumes:
      - ./backend/users-api:/app
      - ./app/node_modules
    depends_on:
      - mysql
    ports:
      - '8000:8000'
    container_name: users-api
  auth-api:
    build: ./backend/auth-api
    env_file:
      - ./env/auth-api.env
    volumes:
      - ./backend/auth-api:/app
      - ./app/node_modules
    depends_on:
      - mysql
    ports:
      - '8001:8001'
    container_name: auth-api
  posts-api:
    build: ./backend/posts-api
    env_file:
      - ./env/posts-api.env
    volumes:
      - ./backend/posts-api:/app
      - ./app/node_modules
    depends_on:
      - mysql
    ports:
      - '8002:8002'
    container_name: posts-api
  mysql:
    image: 'mysql:8.0.30'
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
    container_name: mysqldb
  frontend:
    build: ./frontend
    env_file:
      - ./env/frontend.env
    volumes:
      - ./frontend/src:/app/src
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - users-api
      - auth-api
      - posts-api
    container_name: insta-frontend

volumes:
  data: