version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - ./env/backend.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql
    ports:
      - '8000:8000'
    container_name: insta-backend
  mysql:
    image: 'mysql:8.0.30'
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
    container_name: mysqldb
  frontend:
    build: ./frontend
    env_file:
      - ./env/frontend.env
    volumes:
      - ./frontend/src:/app/src
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - backend
    container_name: insta-frontend

volumes:
  data: