version: '3.8'
services:
  auth-api:
    build: .
    env_file:
      - ./env/auth-api.env
    volumes:
      - .:/app
      - ./app/node_modules
    depends_on:
      - mysql
    ports:
      - '8001:8001'
    container_name: auth-api
  mysql:
    image: 'mysql:8.0.30'
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
    container_name: mysqldb
volumes:
  data: