apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: auth
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - env:
        - name: MYSQL_URL
          value: db-service.default
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              key: jwt
              name: user-jwt
        - name: COOKIE_SECRET
          valueFrom:
            configMapKeyRef:
              key: cookie
              name: user-cookie
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: password
              name: db-user-pass
        image: yeongbin/insta-auth-api:688e2fe
        name: auth
