apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql:8.0.31
          env:
            - name: MYSQL_DATABASE
              value: "database_development"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                configMapKeyRef:
                  name: db-user-pass
                  key: password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-volume
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: host-pvc