apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: posts
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - env:
        - name: MYSQL_URL
          value: db-service.default
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              key: jwt
              name: user-jwt
        - name: COOKIE_SECRET
          valueFrom:
            configMapKeyRef:
              key: cookie
              name: user-cookie
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: password
              name: db-user-pass
        image: yeongbin/insta-posts-api:20ea1d0
        name: posts
