apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: yeongbin/insta-auth-api:latest
          env:
            - name: MYSQL_URL
              value: "db-service.default"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: 
                  name: user-jwt
                  key: jwt
                  optional: False
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef: 
                  name: user-cookie
                  key: cookie
                  optional: False
            - name: MYSQL_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: db-user-pass
                  key: password
                  optional: False