apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: users
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - env:
        - name: MYSQL_URL
          value: db-service.default
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              key: jwt
              name: user-jwt
        - name: COOKIE_SECRET
          valueFrom:
            configMapKeyRef:
              key: cookie
              name: user-cookie
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: password
              name: db-user-pass
        image: yeongbin/insta-users-api:ec0bdd4
        name: users
