apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: yeongbin/insta-users-api:latest
          env:
            - name: MYSQL_URL
              value: "db-service.default"
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef: 
                  name: user-jwt
                  key: jwt
            - name: COOKIE_SECRET
              valueFrom:
                configMapKeyRef: 
                  name: user-cookie
                  key: cookie
            - name: MYSQL_PASSWORD
              valueFrom: 
                configMapKeyRef:
                  name: db-user-pass
                  key: password