name: Users-api main
on: 
  pull_request:
  push:
    branches:
      - 'main'
    paths:
      - './backend/users-api/*'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./backend/users-api/
        run: npm i
      - name: Test code
        working-directory: ./backend/users-api/
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set short git commit SHA
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - name: Build and push (users-api)
        uses: docker/build-push-action@v3
        with:
          context: ./backend/users-api/
          file: ./backend/users-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/insta-users-api:${{ steps.vars.outputs.sha_short }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: yeongbin-hwang/gitops-repo
          ref: main
          token: ${{ secrets.TOKEN_GITHUB}}
          path: gitops-repo
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"
      - name: Kubernetes resources update
        run: |
          cd manifests/users-api
          kustomize edit set image ${{ secrets.DOCKER_HUB_USERNAME }}/insta-users-api:${{ needs.build.outputs.sha_short }}
          kustomize build . -o ../../k8s/users-api/deployment.yaml
          echo "origin kustomization.yaml "
          cat kustomization.yaml 
          echo "updated deployment.yaml "
          cat ../../k8s/users-api/deployment.yaml
      - name: Commit files
        run: |
          git config --local user.email "kyh3565800@kaist.ac.kr"
          git config --local user.name "yeongbin-hwang"
          git commit -am "docker image build and update k8s resources - ${{ needs.build.outputs.sha_short }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        env:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: main