name: Posts-api test and build
on: 
  push:
    branches:
      - 'main'
    paths:
      - './backend/posts-api/*'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./backend/posts-api/
        run: npm i
      - name: Test code
        working-directory: ./backend/posts-api/
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push (users-api)
        uses: docker/build-push-action@v3
        with:
          context: ./backend/posts-api/
          file: ./backend/posts-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/insta-posts-api:latest