name: Docker Deploy
on: 
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push (users-api)
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.working-directory }}/users-api/
          file: ${{ env.working-directory }}/users-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/insta-users-api:latest
      - name: Build and push (auth-api)
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.working-directory }}/auth-api/
          file: ${{ env.working-directory }}/auth-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/insta-auth-api:latest
      - name: Build and push (posts-api)
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.working-directory }}/posts-api/
          file: ${{ env.working-directory }}/posts-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/insta-posts-api:latest
